#!/usr/bin/env npx tsx
/**
 * Create or verify Stripe production assets (products + prices).
 *
 * Usage:
 *   STRIPE_SECRET_KEY=sk_live_... npx tsx scripts/create-stripe-production-assets.ts
 *   npx tsx scripts/create-stripe-production-assets.ts --verify
 *   npx tsx scripts/create-stripe-production-assets.ts --dry-run
 */

import Stripe from 'stripe';
import { config } from 'dotenv';
import { resolve } from 'path';
import { writeFileSync } from 'fs';

// Load .env.local and .env
config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env') });

const PRODUCTS = [
  { name: '2-Day Access', description: 'Perfect for urgent applications - unlimited resumes for 2 days', price: 4.95, tier: '2D' as const },
  { name: '1-Week Access', description: 'Tailor unlimited resumes for a full week', price: 10.0, tier: '7D' as const },
  { name: '1-Month Access', description: 'Comprehensive access for your full job search', price: 20.0, tier: '30D' as const },
];

async function main() {
  const secretKey = process.env.STRIPE_SECRET_KEY;
  if (!secretKey?.startsWith('sk_')) {
    console.error('❌ STRIPE_SECRET_KEY not set. Use: STRIPE_SECRET_KEY=sk_live_... npx tsx scripts/create-stripe-production-assets.ts');
    process.exit(1);
  }

  const verifyOnly = process.argv.includes('--verify');
  const dryRun = process.argv.includes('--dry-run');
  const liveMode = secretKey.startsWith('sk_live_');

  console.log(liveMode ? '🔴 LIVE MODE\n' : '🟡 TEST MODE\n');

  const stripe = new Stripe(secretKey, { apiVersion: '2026-01-28.clover' });
  const priceIds: Record<string, string> = {};

  if (dryRun) {
    console.log('Would create:', PRODUCTS.map((p) => `${p.name} ($${p.price})`).join(', '));
    return;
  }

  if (verifyOnly) {
    const envIds = {
      '2D': process.env.STRIPE_PRICE_ID_2D,
      '7D': process.env.STRIPE_PRICE_ID_7D,
      '30D': process.env.STRIPE_PRICE_ID_30D,
    };
    let allOk = true;
    for (const [tier, id] of Object.entries(envIds)) {
      if (!id) {
        console.log(`❌ STRIPE_PRICE_ID_${tier} not set`);
        allOk = false;
        continue;
      }
      try {
        const p = await stripe.prices.retrieve(id);
        if (p.active) {
          console.log(`✓ ${tier}: ${id} ($${(p.unit_amount || 0) / 100})`);
          priceIds[tier] = id;
        } else {
          console.log(`❌ ${tier}: ${id} exists but is inactive`);
          allOk = false;
        }
      } catch {
        console.log(`❌ ${tier}: ${id} not found`);
        allOk = false;
      }
    }
    if (!allOk) process.exit(1);
    console.log('\n✅ All price IDs verified.');
    printEnvOutput(priceIds);
    return;
  }

  // Create mode
  console.log('🚀 Creating Stripe products and prices...\n');

  for (const product of PRODUCTS) {
    const existingProducts = (await stripe.products.list({ limit: 100 })).data;
    const existing = existingProducts.find((p) => p.name === product.name);
    const stripeProduct = existing || (await stripe.products.create({ name: product.name, description: product.description }));
    if (!existing) console.log(`✓ Created product: "${product.name}"`);
    else console.log(`✓ Product "${product.name}" already exists`);

    const prices = await stripe.prices.list({ product: stripeProduct.id, limit: 100 });
    const existingPrice = prices.data.find((p) => p.unit_amount === Math.round(product.price * 100));
    const price = existingPrice || (await stripe.prices.create({
      product: stripeProduct.id,
      unit_amount: Math.round(product.price * 100),
      currency: 'usd',
    }));
    priceIds[product.tier] = price.id;
    console.log(`✓ Price for "${product.name}": ${price.id}`);
  }

  printEnvOutput(priceIds);
  writeEnvSnippet(priceIds);
  printWebhookInstructions();
}

function printEnvOutput(priceIds: Record<string, string>) {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📋 Add these to your production environment (Vercel, etc.):');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`STRIPE_PRICE_ID_2D=${priceIds['2D']}`);
  console.log(`STRIPE_PRICE_ID_7D=${priceIds['7D']}`);
  console.log(`STRIPE_PRICE_ID_30D=${priceIds['30D']}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('\n✅ Stripe assets ready.');
}

function writeEnvSnippet(priceIds: Record<string, string>) {
  const snippet = `# Stripe Price IDs (add to production env)
# Generated by: npx tsx scripts/create-stripe-production-assets.ts
STRIPE_PRICE_ID_2D=${priceIds['2D']}
STRIPE_PRICE_ID_7D=${priceIds['7D']}
STRIPE_PRICE_ID_30D=${priceIds['30D']}
`;
  const outPath = resolve(process.cwd(), 'stripe-production.env.example');
  writeFileSync(outPath, snippet, 'utf-8');
  console.log(`\n📄 Env snippet written to: stripe-production.env.example`);
}

function printWebhookInstructions() {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📌 Webhook setup (required for payments):');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('1. Go to: https://dashboard.stripe.com/webhooks');
  console.log('2. Add endpoint: https://YOUR_DOMAIN/api/stripe/webhook');
  console.log('3. Select event: checkout.session.completed');
  console.log('4. Copy the signing secret and set STRIPE_WEBHOOK_SECRET in production');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
